### ISSUE TITLE
run "make clean" with sudo wipes out your /bin/ dir !!!

### ISSUE THREAD

**Issue by frankIT** [qwinff/qwinff#40] opened 2019-05-27 19:08 UTC
True it's uncommon to run a `make clean` with `sudo`, but the makefile really need a review considering the risk involved.

It seems that the unset PWD env var cause the issue.
You can safely reproduce with:
`sudo make --dry-run --warn-undefined-variables clean`
> Makefile:52: warning: undefined variable 'PWD'
Makefile:52: warning: undefined variable 'PWD'
Makefile:52: warning: undefined variable 'PWD'
**rm -rf /bin/***
rm -rf /build/*
cd /src && make clean && rm Makefile
/bin/sh: 1: cd: can't cd to /src
Makefile:52: recipe for target 'clean' failed
make: [clean] Error 2 (ignored)

I've compiled from /opt/ and i've been lazy to set proper permissions on the cloned folder, that's why i ran it as su. My system became unbootable and I had a terrible time figuring out what happened. [This script](https://docker.pkg.github.com/ravexina/restore-bin) helped me a ton to properly repopulate /bin/ without reinstall the whole os. Hope nobody else will need to use it.

**Comment by lzh9102** [comment] 2019-05-28 13:53
The problem is fixed in 8a705702303c6de6aadbd57c83cba6cdf4e9e0ad. Sorry for the hassle it causes.

**Closed by lzh9102** 2019-05-28 13:53 UTC
